<?php
/**
 * Created by PhpStorm.
 * User: webwerks
 * Date: 23/10/17
 * Time: 5:07 PM
 */
?>
<div class="page-title">
    <div class="container clearfix">
        <h3 class="text-center">Leads Generated</h3>
    </div>
</div>
<div class="page-content">
    <span class="bg-top"></span>
    <div class="inner-content">
        <div class="container">
            <?php
echo "Leads generated by me : ".$total_generated;
echo "<br><br>Leads converted out of generated :  ".$total_converted;
echo "<br><br>Conversion % :".round(($total_converted/$total_generated)*100,2);
?>
            </div>
        </div>
    <span class="bg-bottom"></span>
</div>

