<?php
$lead_status = $this->config->item('lead_status');
?>
<div class="page-title">
    <div class="container clearfix">
        <h3 class="text-center">Lead Cycle</h3>
    </div>
</div>
<div class="page-content">
    <span class="bg-top"></span>
    <div class="inner-content">
        <div class="container">
            <div class="lead-form">
                <?php
                if(!empty($lead_data)){
                foreach ($lead_data as $key => $value){
                    $fullname = array_map('trim', explode('.', $value['employee_name']));
                    if($fullname[0] == ''){
                        $fullname1 = trim($fullname[1]);
                    }else{
                        $fullname1 = trim($fullname[0]);
                    }
                    $created_by_name = array_map('trim', explode('.', $value['created_by_name']));
                    if($created_by_name[0] == ''){
                        $created_by_name1 = trim($created_by_name[1]);
                    }else{
                        $created_by_name1 = trim($created_by_name[0]);
                    }
                    if(($key+1) % 2 != 0){
                ?>
                <div class="lead-form-left">
                    <div class="form-control">
                        <label>
                            <?php echo "Lead Generated By ".$fullname1." On ".$value['generated_on']; ?>
                        </label>
                    </div>
                    <?php if(!empty($value['assigned_on'])){ ?>
                    <div class="form-control">
                        <label><?php echo "Lead Assigned By ".$created_by_name1." On ".$value['assigned_on'];?></label>
                    </div>
                    <?php }?>

                    <?php if(!empty($value['reroute_from_branch_id'])){?>
                    <div class="form-control">
                        <label><?php echo "Lead Reroute From Branch ".$value['reroute_from_branch_id'];?></label>
                    </div>
                    <div class="form-control">
                        <label><?php echo "Lead Reroute To Branch ".$value['branch_id'];?></label>
                    </div>
                    <?php }?>

                    <?php if(!empty($value['status'])){ ?>
                    <div class="form-control">
                        <label><?php echo "Lead Status : ".$lead_status[$value['status']];?></label>
                    </div>
                    <?php }?>
                </div>
                <?php }else{?>

                <div class="lead-form-right">
                        <div class="form-control">
                            <label>
                                <?php echo "Lead Generated By ".$fullname1." On ".$value['generated_on']; ?>
                            </label>
                        </div>
                        <?php if(!empty($value['assigned_on'])){ ?>
                            <div class="form-control">
                                <label><?php echo "Lead Assigned By ".$created_by_name1." On ".$value['assigned_on'];?></label>
                            </div>
                        <?php }?>

                        <?php if(!empty($value['reroute_from_branch_id'])){?>
                            <div class="form-control">
                                <label><?php echo "Lead Reroute From Branch ".$value['reroute_from_branch_id'];?></label>
                            </div>
                            <div class="form-control">
                                <label><?php echo "Lead Reroute To Branch ".$value['branch_id'];?></label>
                            </div>
                        <?php }?>

                        <?php if(!empty($value['status'])){ ?>
                        <div class="form-control">
                            <label><?php echo "Lead Status : ".$lead_status[$value['status']];?></label>
                        </div>
                </div>
            <?php }}}} ?>
            </div>
    </div>
    <span class="bg-bottom"></span>
</div>